import seaborn as sns
#from pandas.conftest import ascending
ex = sns.load_dataset('exercise')
#print(ex.head(10))
#print(ex.info())
#print(ex['kind'].value_counts())
#print(ex['diet'].value_counts())
#print(ex)
#mpg = sns.load_dataset('mpg')
# print(mpg.head())
# print(mpg.info())
# print(mpg.describe())
# print(mpg['cylinders'].value_counts())
#print(mpg[mpg['horsepower'].isnull()])
#mpg = mpg.drop(columns=['origin', 'model_year', 'name'])
#print(mpg.info())
#print(mpg.head())
# print(mpg.sort_values('mpg', ascending=False))
#mpg['horsepower'] = mpg['horsepower'].fillna(
   # mpg.groupby('cylinders')['horsepower'].transform('median')
#)
#print(mpg.info())
#print(mpg[mpg['horsepower'].isnull()])
# print(mpg[mpg['horsepower'].isnull()])
#print(mpg['model_year'].value_counts().sort_values(ascending=False))
#print(mpg.sort_values('model_year',ascending=False))